### ISSUE TITLE
Integrate Paillier for key generation encryption and ZK Proof

### ISSUE THREAD

**Issue by gbenattar** [KZen-networks/multi-party-ecdsa#12]
This issue is dependent of https://github.com/KZen-networks/multi-party-ecdsa/issues/5. Code has been added to https://github.com/mortendahl/rust-paillier in order to do this. Need to be use in 2 party ECDSA.

**Comment by omershlo** [comment]
reference to the relevant papers for the paillier zk proofs are in comments rust-paillier: proofs/correct_key.rs and range_proof.rs
Paillier encryption is being used in Lindell's paper for Key Generation (protocol 3.1) and Signing (protocol 3.2) https://eprint.iacr.org/2017/552.pdf

**Comment by omershlo** [comment]
reference to the relevant papers for the paillier zk proofs are in comments rust-paillier: proofs/correct_key.rs and range_proof.rs
Paillier encryption is being used in Lindell's paper for Key Generation (protocol 3.1) and Signing (protocol 3.2) https://eprint.iacr.org/2017/552.pdf

**Comment by gbenattar** [comment]
@omershlo You want to take this?

**Comment by mortendahl** [comment]
blocked, waiting for 15/7 release of rust-paillier

**Comment by gbenattar** [comment]
@omershlo I believe this is done but it is currently using the dev branch of rust-paillier. 

I am in favor of resolving it and creating a new issue to switch branch. What do you think?
