### ISSUE TITLE
Implement signing protocol

### ISSUE THREAD

**Issue by omershlo** [KZen-networks/multi-party-ecdsa#20]
based on protocol 3.2 in https://eprint.iacr.org/2017/552.pdf : 
- steps 1,2,3 are identical to Key Generation protocol but with ephemeral secret keys
- steps 4,5 require use of Paillier cryptosystem. Using the same ek and dk from Key Generation protocol. We can use  https://github.com/mortendahl/rust-paillier for Paillier.

**Comment by omershlo** [comment]
@gbenattar any progress ?

**Comment by omershlo** [comment]
see #24

**Comment by gbenattar** [comment]
Can we close it?
