### ISSUE TITLE
error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by mazhiyu** [KZen-networks/multi-party-ecdsa#66]
ld: library not found for -lgmp 
clang: error: linker command failed with exit code 1

rustc --version
rustc 1.36.0-nightly (a9ec99f42 2019-05-13)

**Comment by mazhiyu** [comment]
brew install gmp

**Comment by phpmaple** [comment]
brew install gmp, but same problem also

**Comment by omershlo** [comment]
what error you see? 
you might need to make sure the path GMP is installed is in a path where the compiler is looking

**Comment by phpmaple** [comment]
`error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.0.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.1.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.10.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.11.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.12.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.13.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.14.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.15.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.2.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.3.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.4.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.5.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.6.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.7.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.8.rcgu.o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.gg18_keygen_client.5nu1yemr-cgu.9.rcgu.o" "-o" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/examples/gg18_keygen_client-ab6bfdc480fd2ec0.12jeoiyws60m4hu0.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps" "-L" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/build/secp256k1-3bb514bb878bb57a/out" "-L" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/build/backtrace-sys-6ff240c7d62db4b8/out" "-L" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/build/rust-crypto-a68128ed1214fd96/out" "-L" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libreqwest-2088c697fe0b056f.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libuuid-8ea5b246bf8040a0.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libserde_urlencoded-919d89bd102a8f08.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libdtoa-c7fe4ba8712a8d18.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libmime_guess-6b4d794945a9aa39.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libunicase-d5cd960c56580eca.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libmime-ff076852b20a5f69.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libflate2-26927eaf7488cf8d.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libminiz_oxide-7e777f1543b0ab78.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libadler32-56df6d262eb74827.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcrc32fast-b252c46bc712a50c.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libhyper-d485d9961802ca3d.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libwant-a526efd42b57e9a5.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtry_lock-4bddd59031b4ce57.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio-bbbba7f97751dd67.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio_timer-4001c1a94496267b.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio_threadpool-ae19d407d1656734.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio_tcp-689f64f26600b3bd.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio_reactor-b28f4cfeb3c13053.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio_sync-0c280ebe4b88cc64.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libparking_lot-235d76935e7f0f87.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libparking_lot_core-b8255e8dfa136f50.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/liblock_api-5052355fbd2c2f83.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio_current_thread-d2b3f982d3225e1c.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio_executor-447fbd7b0906411e.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libmio-0c1150112e1d5bfa.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libnet2-2257627bc4ffeeef.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libhttparse-69543746b625344d.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libhttp_body-22d12534caf11bec.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio_buf-2fbb7465b1ed6b40.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libh2-2d679f934779b75f.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libindexmap-d433926e1f26b510.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libstring-5647194f447aa0b2.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libslab-f563b383454ea644.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtokio_io-fd7d7778663f03a5.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libfutures_cpupool-7c81071045680250.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libhttp-f18a19552562131c.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libfnv-9b14a0d65784d360.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libfutures-c310653aa9ed7b5c.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libencoding_rs-237bbac5354c7992.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcookie_store-27f90ff77ed9a9cd.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/liblog-51ce264bdaa444f9.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libpublicsuffix-39874a3da81bb1ab.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/liburl-ac9f7f39b408daf5.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libpercent_encoding-0a54058e0eaa446c.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libidna-6fb74efbeb87e418.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libregex-1964d3c48ca096f1.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libthread_local-e5cc7fb7536f2686.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libregex_syntax-5d37d12c32ab9dea.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libaho_corasick-88e50bb9666bed98.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libmemchr-769b5a870f50e5db.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/liberror_chain-7fb1c92312af2d41.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtry_from-cc302f3dcfa7f88a.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libfailure-631ed952c3c7234f.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libbacktrace-ed86a48d8782584c.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libbacktrace_sys-1a955f225d2ab557.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librustc_demangle-c9ac5c4ff23d7b41.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcookie-ad87e2ee96f066fe.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/liburl-4f38a1b6601488a1.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libpercent_encoding-c44aa33cf4e4ca24.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libidna-57ca8c13b536af4d.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libunicode_normalization-0247cde7a32580aa.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libsmallvec-14b0542a8ac25071.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libunicode_bidi-11e180465d090f63.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libmatches-10cf8055db863958.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libbytes-9296916915269ce5.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libiovec-79e033a5f24b0e81.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libbase64-291cf0e240c56fe7.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libmulti_party_ecdsa-c0840d1e1cd52fcc.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libzk_paillier-7d880117b233dc07.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libbit_vec-6ae94125075638fe.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libpaillier-e6bdce30a8fca907.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcentipede-a7633f7e6f78ae92.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librayon-92c54af622160055.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librayon_core-f4aa20ea7fbd119b.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libnum_cpus-9a033c5865405fd2.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcrossbeam_queue-2ad63b13b9373f88.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcrossbeam_deque-fc6156cbbaf21bc9.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcrossbeam_epoch-a3c54b31c806bf09.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libscopeguard-5786670be6ecb05e.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libmemoffset-58ca2def28b6eed5.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcrossbeam_utils-5c97b9ba0facd017.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/liblazy_static-33288c67e2ab2836.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcfg_if-cd829b2628f2ccf1.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libbulletproof-36ccdc3b7b9a7c43.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libitertools-c374869c247d262b.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libeither-b1a84e6d64ab5b49.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libsubtle-cb4d234536d562b4.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcurv-6f3275afeaa41a70.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libhmac-5dee35996ac6ad17.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcrypto_mac-e999d23323b7f5bc.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libsubtle-613d6fb962311059.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libsha2-f24b4bb179da8819.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libfake_simd-a0f90b1f7c33f1f8.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libblake2b_simd-fd64cb4419936200.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libconstant_time_eq-a8a62b6d0c8f3d8e.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libarrayvec-4a7886788e3957cf.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libnodrop-94101ddae7aeaecf.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libarrayref-2e0772a2a8547330.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libsha3-9c59279916c3735c.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libdigest-faa087b6a487238e.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libopaque_debug-5886b3c9f6e69647.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libblock_buffer-e2683272e26f2fef.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libgeneric_array-70b415c54fbe8efe.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtypenum-135dfb97cfdf8963.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libblock_padding-8a27284824624118.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libbyte_tools-51491f8f43d822d1.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libbyteorder-31e9eaba65004767.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libkeccak-88ce83668771ed88.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libgmp-48417328c986bcc2.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libserde_json-3794977f1479d321.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libryu-52a174aaedfbdd3b.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libitoa-8b72185ff4b92aaa.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libnum_traits-005309a07991a641.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libzeroize-a46f4dbbe37db456.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libsecp256k1-634d12bae239e4ee.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libserde-e4e240dd8dcd0ece.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand-5ca0260611f1082b.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand_xorshift-6a5e6e5355b61679.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand_pcg-ac156ad9e7b9357f.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand_hc-3cf5e16cfcfe12be.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand_chacha-a419a66a23b8d140.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand_isaac-32aca341223255af.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand_core-6702a6022b01d390.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand_os-81023786dd09c77a.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand_jitter-0112df8b920d8192.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand_core-20b4e24ef7227ded.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libcrypto-14aa87bb71606c98.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/libtime-e01465df22ada604.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librustc_serialize-23708f3f970cb082.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand-8f48265c2a35256c.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/librand-ed30eff289de1f83.rlib" "/Users/koofrank/Documents/rust/multi-party-ecdsa/target/release/deps/liblibc-9dc26a1ad1fd17f3.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-a104564b5cd85c3c.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-b8538eedc7e0aa47.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace-c7f6a23a8e1e3f0d.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libbacktrace_sys-0f0fd6cb2d0ffa02.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-03c3af5ce910211b.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-17cc4f6d2f17ab1d.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-df043cce83b6dd34.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-0f97cfed0ef82f67.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-6308b422d34f5adf.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-9cd6fde8086e33c8.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-ac5b59d7ac33292f.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-aededee92e955f4b.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-093e765cd9bdca1f.rlib" "/Users/koofrank/.rustup/toolchains/nightly-2019-09-05-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-967a7c840affa3a2.rlib" "-lgmp" "-lgmp" "-lgmp" "-lgmp" "-lgmp" "-framework" "Security" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: library not found for -lgmp
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by phpmaple** [comment]
Solved, sudo cargo build --release --examples, it works, I worked with `sudo`

**Comment by Hrezaei** [comment]
> Solved, sudo cargo build --release --examples, it works, I worked with `sudo`

Even with sudo, didn't worked for me!

> you might need to make sure the path GMP is installed is in a path where the compiler is looking

Where the compiler is looking?

GMP is installed in these paths:
```
$ brew --prefix gmp

/opt/homebrew/opt/gmp
```

and
```
$ port content gmp

Port gmp contains:
  /opt/local/include/gmp.h
  /opt/local/include/gmpxx.h
  /opt/local/lib/libgmp.10.dylib
  /opt/local/lib/libgmp.a
  /opt/local/lib/libgmp.dylib
  /opt/local/lib/libgmpxx.4.dylib
  /opt/local/lib/libgmpxx.a
  /opt/local/lib/libgmpxx.dylib
  /opt/local/lib/pkgconfig/gmp.pc
  /opt/local/lib/pkgconfig/gmpxx.pc
  /opt/local/share/info/gmp.info
  /opt/local/share/info/gmp.info-1
  /opt/local/share/info/gmp.info-2
```

**Comment by timoth-y** [comment]
Finally done with this issue on Mac (M1)!

1. Ensure Xcode command-line tools are installed:
```
xcode-select --reset && xcode-select --install
```
> I've also installed Xcode itself, but it didn't make any difference besides eating a lot of space!

2. Install `libgmp`: 
```bash
brew install gmp
```

3. Finally, make sure `rustc` can locate installed lib (put this in `.zshrc` or alike):
```
export LIBRARY_PATH=$LIBRARY_PATH:/opt/homebrew/lib
export INCLUDE_PATH=$INCLUDE_PATH:/opt/homebrew/include
```
The latter was a final piece of the puzzle for me. Hope that would be also enough for you!
