### ISSUE TITLE
`t` and `n` should not be usize

### ISSUE THREAD

**Issue by kigawas** [KZen-networks/multi-party-ecdsa#72]
`usize` in Rust is for something related with memory address offset, not for counting number.

Ref: https://users.rust-lang.org/t/i32-vs-isize-u32-vs-usize/22657/2

**Comment by kigawas** [comment]
Suggest using u16 or u32 here

**Comment by omershlo** [comment]
good catch, I think I repeatedly made this mistake. 
https://github.com/KZen-networks/multi-party-ecdsa/commit/9c1121ab9db37a58d4ee8979356454e680619a76 
I changed it on my branch - can you please review ?

**Comment by kigawas** [comment]
LGTM
I suggest merging #71 first
