### ISSUE TITLE
how to export the pubkey when use gg18_keygen_client ?

### ISSUE THREAD

**Issue by paizzj** [KZen-networks/multi-party-ecdsa#90]
follow the multi-party-ecdsa demo, when keygen use gg18_keygen_client, the output file  keys.store, that is a json file.
what's the mean of all fields ?  especially how to  generate the pubkey based on keys.store file ?

**Comment by omershlo** [comment]
Hi, 

The fields are basically the outputs of the distributed key generation of GG19 (https://github.com/KZen-networks/multi-party-ecdsa/blob/master/docs/gg19.pdf). 
It is pretty much 1:1 with the paper. 

As part of the key generation each party must learn the joint public key. 
the last field is this public key. Make sure that it is the same value for all parties. 

Please let me know if you have more questions or need more details.

**Comment by paizzj** [comment]
thanks a lot.

**Comment by elpddev** [comment]
Thank you for a great library.

How to take the last part that is the number array and convert it to public key?
